spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://172.27.0.3:3306/customerdb}
    username: ${DATASOURCE_USERNAME:usrdb}
    password: ${DATASOURCE_PASSWORD:passdb}
  jpa:
    hibernate.ddl-auto: none
    show-sql: false
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  flyway:
    check-location: true
    enabled: true