spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://172.27.0.3:3306/customerdb}
    username: ${DATASOURCE_USERNAME:usrdb}
    password: ${DATASOURCE_PASSWORD:passdb}
  jpa:
    hibernate.ddl-auto: none
    show-sql: false
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  flyway:
    check-location: true
    enabled: true
management:
  endpoints.web.exposure.include: '*'
  metrics.export.prometheus.enabled: true
  endpoint:
    metrics.enabled: false
    prometheus.enabled: true
    shutdown.enabled: true
    health:
      show-details: always
      probes.enabled: true
      livenessState.enabled: true
      readinessState.enabled: true