version: '3.3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: customer_db
      MYSQL_USER: usr_db
      MYSQL_PASSWORD: pass_db
    ports:
      - "3306:3306"