version: '3.3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: customerdb
      MYSQL_USER: usrdb
      MYSQL_PASSWORD: passdb
    ports:
      - "3306:3306"
    volumes:
      - 'docker_data:/data/var/lib/mysql'

  portainer:
    image: portainer/portainer-ce
    restart: always
    ports:
      - '9000:9000'
    volumes:
      - 'docker_data:/data/var/lib/portainer'
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  docker_data:
